/* Creating a core objects of a Enterprise data ware house */
USE ROLE SYSADMIN;

/* Create Database ACDP */
CREATE DATABASE IF NOT EXISTS ACDP;

USE DATABASE ACDP;

/* Create different schemas in ACDP database */
CREATE SCHEMA IF NOT EXISTS LANDING;
CREATE SCHEMA IF NOT EXISTS CONFORMED;
CREATE SCHEMA IF NOT EXISTS STG_CONFORMED;
CREATE SCHEMA IF NOT EXISTS REFINED;
CREATE SCHEMA IF NOT EXISTS STG_REFINED;
CREATE SCHEMA IF NOT EXISTS OUTPUT;
CREATE SCHEMA IF NOT EXISTS STG_OUTPUT;

