/* Grant Access to role on database */
Use ROLE USERADMIN;

/* ACDP_ADMIN */
Grant All on Database ACDP to ROLE ACDP_ADMIN;
Grant All on Database ACDP to ROLE ACDP_ADMIN;
Grant ALL on  SCHEMA ACDP.LANDING to ROLE ACDP_ADMIN;
Grant ALL on  SCHEMA ACDP.CONFORMED to ROLE ACDP_ADMIN;
Grant ALL on  SCHEMA ACDP.STG_CONFORMED to ROLE ACDP_ADMIN;
Grant ALL on  SCHEMA ACDP.REFINED to ROLE ACDP_ADMIN;
Grant ALL on  SCHEMA ACDP.STG_REFINED to ROLE ACDP_ADMIN;
Grant ALL on  SCHEMA ACDP.OUTPUT to ROLE ACDP_ADMIN;
Grant ALL on  SCHEMA ACDP.STG_OUTPUT to ROLE ACDP_ADMIN;


/*ACDP_ENGINEER */

Grant USAGE on Database ACDP to ROLE ACDP_ENGINEER;
Grant USAGE on  SCHEMA ACDP.LANDING to ROLE ACDP_ENGINEER;
Grant USAGE on  SCHEMA ACDP.CONFORMED to ROLE ACDP_ENGINEER;
Grant USAGE on  SCHEMA ACDP.STG_CONFORMED to ROLE ACDP_ENGINEER;
Grant USAGE on  SCHEMA ACDP.REFINED to ROLE ACDP_ENGINEER;
Grant USAGE on  SCHEMA ACDP.STG_REFINED to ROLE ACDP_ENGINEER;
Grant USAGE on  SCHEMA ACDP.OUTPUT to ROLE ACDP_ENGINEER;
Grant USAGE on  SCHEMA ACDP.STG_OUTPUT to ROLE ACDP_ENGINEER;


/*ACDP_ANALYST */
Grant USAGE on Database ACDP to ROLE ACDP_ANALYST;
Grant USAGE on  SCHEMA ACDP.CONFORMED to ROLE ACDP_ANALYST;
Grant USAGE on  SCHEMA ACDP.REFINED to ROLE ACDP_ANALYST;
Grant USAGE on  SCHEMA ACDP.OUTPUT to ROLE ACDP_ANALYST;

/*ACDP_REPORT */
Grant USAGE on Database ACDP to ROLE ACDP_REPORT;
Grant USAGE on  SCHEMA ACDP.REFINED to ROLE ACDP_REPORT;
Grant USAGE on  SCHEMA ACDP.OUTPUT to ROLE ACDP_REPORT;
